title       = "wikifeatured"
baseURL     = "https://wikifeatured-cli.tamnd.com/"
description = "A command line for wikifeatured."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/wikifeatured-cli"
